### ISSUE TITLE
Error in running profiles

### ISSUE THREAD

**Issue by jinankjain** [Greennav/gn-profiles#6]
![err](https://cloud.githubusercontent.com/assets/3854904/13556539/08d9f7ee-e402-11e5-9790-a4b1d95207eb.png)

**Comment by fabianbormann** [comment]
hey @jinankjain, this is a "known" issue but thanks for make it public! :)
The gn-profiles is written against an old server version. The building of a new server architecture and the extension of gn-profiles are both GSoC projects.

**Comment by jinankjain** [comment]
@fabianbormann I would like to work on this GSOC projects

**Comment by fabianbormann** [comment]
@jinankjain very cool that your interested in this project and we love to see your proposal! It seems that you are very motivated :+1:  ;)

**Comment by jinankjain** [comment]
@fabianbormann I would like to talk to you about my proposal is there any of mailing list or gitter where we could discuss about this?

**Comment by maxlorenz** [comment]
Hi @jinankjain,

right now please just send mails to any of us to discuss your proposal. The mailling list will be opened later this week :smile:

**Comment by jinankjain** [comment]
@maxlorenz @fabianbormann Could you please share your mailing id as I was unable to find them.
